# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cplex_vrp.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "cplex_vrp.Matrix" do
    repeated :id, :int32, 1
    repeated :time, :float, 2
    repeated :distance, :float, 3
    repeated :value, :float, 4
  end
  add_message "cplex_vrp.TimeWindow" do
    optional :start, :int64, 2
    optional :end, :int64, 3
  end
  add_message "cplex_vrp.Service" do
    repeated :time_windows, :message, 1, "cplex_vrp.TimeWindow"
    repeated :quantities, :int32, 2
    optional :matrix_index, :uint32, 3
    optional :id, :string, 4
    optional :duration, :int64, 5
  end
  add_message "cplex_vrp.Capacity" do
    optional :limit, :int32, 1
    optional :overload_multiplier, :float, 2
    optional :counting, :bool, 3
  end
  add_message "cplex_vrp.Vehicle" do
    optional :id, :string, 1
    repeated :capacities, :message, 2, "cplex_vrp.Capacity"
    optional :time_window, :message, 3, "cplex_vrp.TimeWindow"
    optional :matrix_index, :uint32, 4
    optional :start_index, :int32, 5
    optional :end_index, :int32, 6
    optional :day_index, :int32, 7
    optional :value_matrix_index, :uint32, 8
  end
  add_message "cplex_vrp.Route" do
    optional :vehicle_id, :string, 1
    repeated :service_ids, :string, 2
  end
  add_message "cplex_vrp.Problem" do
    repeated :vehicles, :message, 1, "cplex_vrp.Vehicle"
    repeated :services, :message, 2, "cplex_vrp.Service"
    repeated :matrices, :message, 3, "cplex_vrp.Matrix"
    repeated :routes, :message, 4, "cplex_vrp.Route"
  end
end

module CplexVrp
  Matrix = Google::Protobuf::DescriptorPool.generated_pool.lookup("cplex_vrp.Matrix").msgclass
  TimeWindow = Google::Protobuf::DescriptorPool.generated_pool.lookup("cplex_vrp.TimeWindow").msgclass
  Service = Google::Protobuf::DescriptorPool.generated_pool.lookup("cplex_vrp.Service").msgclass
  Capacity = Google::Protobuf::DescriptorPool.generated_pool.lookup("cplex_vrp.Capacity").msgclass
  Vehicle = Google::Protobuf::DescriptorPool.generated_pool.lookup("cplex_vrp.Vehicle").msgclass
  Route = Google::Protobuf::DescriptorPool.generated_pool.lookup("cplex_vrp.Route").msgclass
  Problem = Google::Protobuf::DescriptorPool.generated_pool.lookup("cplex_vrp.Problem").msgclass
end
